import React from "react";
import './LoadingPage.scss';
const LoadingPage = () => {
  return (
    <div className="loadingContent ">
      <div className="loadingio-spinner-bean-eater-ess3b3jg9za">
        <div className="ldio-ayr9nwyqenh">
          <div>
            <div />
            <div />
            <div />
          </div>
          <div>
            <div />
            <div />
            <div />
          </div>
        </div>
      </div>
      <style
        type="text/css"
        dangerouslySetInnerHTML={{
          __html:
            "\n@keyframes ldio-ayr9nwyqenh-1 {\n    0% { transform: rotate(0deg) }\n   50% { transform: rotate(-45deg) }\n  100% { transform: rotate(0deg) }\n}\n@keyframes ldio-ayr9nwyqenh-2 {\n    0% { transform: rotate(180deg) }\n   50% { transform: rotate(225deg) }\n  100% { transform: rotate(180deg) }\n}\n.ldio-ayr9nwyqenh > div:nth-child(2) {\n  transform: translate(-15px,0);\n}\n.ldio-ayr9nwyqenh > div:nth-child(2) div {\n  position: absolute;\n  top: 40px;\n  left: 40px;\n  width: 120px;\n  height: 60px;\n  border-radius: 120px 120px 0 0;\n  background: #fb4226;\n  animation: ldio-ayr9nwyqenh-1 1s linear infinite;\n  transform-origin: 60px 60px\n}\n.ldio-ayr9nwyqenh > div:nth-child(2) div:nth-child(2) {\n  animation: ldio-ayr9nwyqenh-2 1s linear infinite\n}\n.ldio-ayr9nwyqenh > div:nth-child(2) div:nth-child(3) {\n  transform: rotate(-90deg);\n  animation: none;\n}@keyframes ldio-ayr9nwyqenh-3 {\n    0% { transform: translate(190px,0); opacity: 0 }\n   20% { opacity: 1 }\n  100% { transform: translate(70px,0); opacity: 1 }\n}\n.ldio-ayr9nwyqenh > div:nth-child(1) {\n  display: block;\n}\n.ldio-ayr9nwyqenh > div:nth-child(1) div {\n  position: absolute;\n  top: 92px;\n  left: -8px;\n  width: 16px;\n  height: 16px;\n  border-radius: 50%;\n  background: #00be00;\n  animation: ldio-ayr9nwyqenh-3 1s linear infinite\n}\n.ldio-ayr9nwyqenh > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }\n.ldio-ayr9nwyqenh > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }\n.ldio-ayr9nwyqenh > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }\n.loadingio-spinner-bean-eater-ess3b3jg9za {\n  width: 200px;\n  height: 200px;\n  display: inline-block;\n  overflow: hidden;\n  background: #f1f2f3;\n}\n.ldio-ayr9nwyqenh {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  transform: translateZ(0) scale(1);\n  backface-visibility: hidden;\n  transform-origin: 0 0; /* see note above */\n}\n.ldio-ayr9nwyqenh div { box-sizing: content-box; }\n/* generated by https://loading.io/ */\n",
        }}
      />
    </div>
  );
};

export default LoadingPage;
