export const GET_CINEMA_LIST_REQUEST = "GET_CINEMA_LIST_REQUEST";
export const GET_CINEMA_LIST_SUCCESS = "GET_CINEMA_LIST_SUCCESS";
export const GET_CINEMA_LIST_FAIL = "GET_CINEMA_LIST_FAIL";

export const GET_CINEMA_BY_MOVIE_REQUEST = "GET_CINEMA_BY_MOVIE_REQUEST";
export const GET_CINEMA_BY_MOVIE_SUCCESS = "GET_CINEMA_BY_MOVIE_SUCCESS";
export const GET_CINEMA_BY_MOVIE_FAIL = "GET_CINEMA_BY_MOVIE_FAIL";
